#!/usr/bin/env bash
#This script displays 1 to 100 
#"Fizz" for multiples of 3 
#"Buzz" for multiples of 5
#"FizzBuzz" for multiples of 3 and 5
i=1
while [ $i -le 100 ]
do
	if (( $(( i % 3 ))  == 0 && $(( i % 5 )) == 0 ))
	then
		echo "FizzBuzz"
	elif [ $(( i % 3 ))  == 0 ]
	then
		echo "Fizz"
	elif [ $(( i % 5 )) == 0 ]
	then
		echo "Buzz"
	else
		echo $i
	fi
	i=$(( i + 1))
done
